### PR TITLE
Add a command to list all available libraries

### PR DESCRIPTION
**Pull request by choeger**
Signed-off-by: Christoph Höger <christoph.hoeger@tu-berlin.de>

### CODE REVIEW

**Comment by dietmarw** [comment]
I think you should split this PR into two.

**Comment by choeger** [comment]
Since  04830ce is a no-brainer, I don't intend to make it a separete pull-request. I just fixed it along the way.

**Comment by dietmarw** [comment]
OK the title of the PR was just misleading then.

**Comment by xogeny** [comment]
Excellent.  Thanks for contributing this.

**Pull request merged**
